export default [
    "Approximate Location (Mandatory)",
    "Approximate Location (Optional)",
    "Precise Location (Mandatory)",
    "Precise Location (Optional)",
    "Name (Mandatory)",
    "Name (Optional)",
    "Email address Mandatory",
    "Email address Optional",
    "User IDs Mandatory",
    "User IDs Optional",
    "Address Mandatory",
    "Address Optional",
    "Phone number Mandatory",
    "Phone number Optional",
    "Political or religious beliefs Mandatory",
    "Political or religious beliefs Optional",
    "Sexual orientation Mandatory",
    "Sexual orientation Optional",
    "Other info Mandatory",
    "Other info Optional",
    "User payment info Mandatory",
    "User payment info Optional",
    "Purchase history Mandatory",
    "Purchase history Optional",
    "Credit score Mandatory",
    "Credit score Optional",
    "Other financial info Mandatory",
    "Other financial info Optional",
    "Health info Mandatory",
    "Health info Optional",
    "Fitness Info Mandatory",
    "Fitness Info Optional",
    "Emails Mandatory",
    "Emails Optional",
    "SMS or MMS Mandatory",
    "SMS or MMS Optional",
    "Other in-app messages Mandatory",
    "Other in-app messages Optional",
    "Photos Mandatory",
    "Photos Optional",
    "Videos Mandatory",
    "Videos Optional",
    "Voice or sound recordings Mandatory",
    "Voice or sound recordings Optional",
    "Music files Mandatory",
    "Music files Optional",
    "Other audio files Mandatory",
    "Other audio files Optional",
    "Files and docs Mandatory",
    "Files and docs Optional",
    "Calendar events Mandatory",
    "Calendar events Optional",
    "Contacts Mandatory",
    "Contacts Optional",
    "In-app search history Mandatory",
    "In-app search history Optional",
    "App interactions Mandatory",
    "App interactions Optional",
    "Installed apps Mandatory",
    "Installed apps Optional",
    "Other user-generated content Mandatory",
    "Other user-generated content Optional",
    "Other actions Mandatory",
    "Other actions Optional",
    "Web browsing history Mandatory",
    "Web browsing history Optional",
    "Crash logs Mandatory",
    "Crash logs Optional",
    "Diagnostics Mandatory",
    "Diagnostics Optional",
    "Other app performance data Mandatory",
    "Other app performance data Optional",
    "Device or other IDs Mandatory",
    "Device or other IDs Optional",
    "Approximate Location",
    "Precise location",
    "Name",
    "Email address",
    "User IDs",
    "Address",
    "Phone number",
    "Sexual orientation",
    "Other info",
    "User payment info",
    "Other financial info",
    "Purchase history",
    "Credit Score ",
    "Health info",
    "Photos",
    "Videos",
    "App interactions",
    "Other user-generated content",
    "In-app search history",
    "Other actions",
    "Crash logs",
    "Diagnostics",
    "Other app performance data",
    "Device or other IDs",
    "Data is encrypted in transit",
    "Data can’t be deleted",
    "You can request that data be deleted",
    "Independent security review"
]