export default [
  "Approximate location",
  "Approximate location · Optional",
  "Precise location",
  "Precise location · Optional",
  "Name",
  "Name · Optional",
  "Email address",
  "Email address · Optional",
  "User IDs",
  "User IDs · Optional",
  "Address",
  "Address · Optional",
  "Phone number",
  "Phone number · Optional",
  "Race and ethnicity",
  "Race and ethnicity · Optional",
  "Political or religious beliefs",
  "Political or religious beliefs · Optional",
  "Sexual orientation",
  "Sexual orientation · Optional",
  "Other info",
  "Other info · Optional",
  "User payment info",
  "User payment info · Optional",
  "Purchase history",
  "Purchase history · Optional",
  "Credit score",
  "Credit score · Optional",
  "Other financial info",
  "Other financial info · Optional",
  "Health info",
  "Health info · Optional",
  "Fitness info",
  "Fitness info · Optional",
  "Emails",
  "Emails · Optional",
  "SMS or MMS",
  "SMS or MMS · Optional",
  "Other in-app messages",
  "Other in-app messages · Optional",
  "Photos",
  "Photos · Optional",
  "Videos",
  "Videos · Optional",
  "Voice or sound recordings",
  "Voice or sound recordings · Optional",
  "Music files",
  "Music files · Optional",
  "Other audio files",
  "Other audio files · Optional",
  "Files and docs",
  "Files and docs · Optional",
  "Calendar events",
  "Calendar events · Optional",
  "Contacts",
  "Contacts · Optional",
  "App interactions",
  "App interactions · Optional",
  "In-app search history",
  "In-app search history · Optional",
  "Installed apps",
  "Installed apps · Optional",
  "Other user-generated content",
  "Other user-generated content · Optional",
  "Other actions",
  "Other actions · Optional",
  "Web browsing history",
  "Web browsing history · Optional",
  "Crash logs",
  "Crash logs · Optional",
  "Diagnostics",
  "Diagnostics · Optional",
  "Other app performance data",
  "Other app performance data · Optional",
  "Device or other IDs",
  "Device or other IDs · Optional",
];
